"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](blue)$username$hostname[](fg:blue)
[│](blue)$directory$git_branch$git_metrics$git_state$git_status$dotnet$lua$nodejs
[└─](blue)$battery$status[>](blue) """

continuation_prompt = "[>](bright-black) "

[character]
success_symbol = "[▶](bold green)"

[battery]
disabled = false
full_symbol = "  "
charging_symbol = "  "
discharging_symbol = "  "
unknown_symbol = "  "
empty_symbol = "  "

[[battery.display]]
threshold = 80

[git_metrics]
disabled = false
format = "([$added]($added_style) )([ $deleted]($deleted_style) )"

[dotnet]
disabled = false
format = "\n[│](blue)(🎯 $tfm) via $symbol($version)]($style)"

[lua]
symbol = " "
format = "\n[│](blue)[$symbol($version)]($style)"

[nodejs]
format = "\n[│](blue)[$symbol($version)]($style)"
symbol = " "

[package]
disabled = true

[status]
disabled = false
format = "[$symbol]($style)"
map_symbol = true
symbol = ""

[directory]
truncation_symbol = "…\\"
read_only = " "

[directory.substitutions]
"Documents" = " "
"Dokumente" = " "
"Downloads" = " "
"Music" = " "
"Musik" = " "
"Pictures" = " "
"Bilder" = " "
"Images" = " "

[git_branch]
symbol = " "

[username]
show_always = true
style_user = "bg:blue fg:white bold"
style_root = "bg:blue fg:white bold"
format = '[$user]($style)'

[git_status]
stashed = ""
staged = ""
deleted = ""
style = "yellow bold"
ignore_submodules = true

[hostname]
disabled = false
ssh_only = false
format = "[@$ssh_symbol$hostname]($style)"
style = "bg:blue fg:white bold"
